### ISSUE TITLE
annotation of rgb frames pkl

### ISSUE THREAD

**Issue by Yingying6** [bensange123/Papers#1]
Thank you for your good summary.
I wonder where did you get frames_dict_tr.pkl / frames_dict_te.pkl in [Charades](https://github.com/bensange123/Papers/blob/master/1行为识别/2Timeception%20for%20Complex%20Action%20Recognition/timeception-master/datasets/charades.py)

many thanks

**Comment by bensange123** [comment]
https://github.com/bensange123/Papers/blob/master/1%E8%A1%8C%E4%B8%BA%E8%AF%86%E5%88%AB/2Timeception%20for%20Complex%20Action%20Recognition/timeception-master/datasets/charades.py  in 314 line

**Comment by Yingying6** [comment]
Yes thanks.
Comprehensive survey and practice! good job!
