### ISSUE TITLE
纯时间卷积前的通道分组操作

### ISSUE THREAD

**Issue by Yingying6** [bensange123/Papers#2]
我在理解原论文‘to this end, we propose a channel grouping operation before the temporal-only convolution'时感到很疑惑，正好你的论文笔记也提到了这点，想和你讨论一下。
我理解channel grouping的目的就是为了减少参数，作者为什么认为它能解决空间语义信息缺失的问题呢？你在论文笔记里也提到了这是对空间信息处理的改进。这个我不明白。
谢谢分享。

**Comment by Yingying6** [comment]
> 我在理解原论文‘to this end, we propose a channel grouping operation before the temporal-only convolution'时感到很疑惑，正好你的论文笔记也提到了这点，想和你讨论一下。
> 我理解channel grouping的目的就是为了减少参数，作者为什么认为它能解决空间语义信息缺失的问题呢？你在论文笔记里也提到了这是对空间信息处理的改进。这个我不明白。
> 谢谢分享。

sorry I forgot to mention this is about Timeception..

**Comment by bensange123** [comment]
1006963297，加我qq，细聊
 
------------------
Best  regardPengzhen Ren




 




------------------ 原始邮件 ------------------
发件人: "Yingying6"<notifications@github.com>; 
发送时间: 2019年9月20日(星期五) 下午4:32
收件人: "bensange123/Papers"<Papers@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [bensange123/Papers] 纯时间卷积前的通道分组操作 (#2)



 
我在理解原论文‘to this end, we propose a channel grouping operation before the temporal-only convolution'时感到很疑惑，正好你的论文笔记也提到了这点，想和你讨论一下。
 我理解channel grouping的目的就是为了减少参数，作者为什么认为它能解决空间语义信息缺失的问题呢？你在论文笔记里也提到了这是对空间信息处理的改进。这个我不明白。
 谢谢分享。
  
sorry I forgot to mention this is about Timeception..
 
&mdash;

**Comment by bensange123** [comment]
> 我在理解原论文‘to this end, we propose a channel grouping operation before the temporal-only convolution'时感到很疑惑，正好你的论文笔记也提到了这点，想和你讨论一下。
> 我理解channel grouping的目的就是为了减少参数，作者为什么认为它能解决空间语义信息缺失的问题呢？你在论文笔记里也提到了这是对空间信息处理的改进。这个我不明白。
> 谢谢分享。

对于这个问题我也没有合适的思路。
想请教下这个问题：https://github.com/Jiankai-Sun/charades-baseline-pytorch/blob/d34178a216c5333fb193dc731c77ceaad54bb346/utils/map.py#L26
m_ap = np.mean(m_aps)
m_ap = np.nanmean(m_aps)
这两种情况对结果会有影响吗，有什么不同吗，为啥我找到了在这个Charades数据集上面两种不一样的评价指标。使用m_ap = np.mean(m_aps)开始时一直都是nan，不知道后面会不会时正常的数字

**Comment by Yingying6** [comment]
> > 我在理解原论文‘to this end, we propose a channel grouping operation before the temporal-only convolution'时感到很疑惑，正好你的论文笔记也提到了这点，想和你讨论一下。
> > 我理解channel grouping的目的就是为了减少参数，作者为什么认为它能解决空间语义信息缺失的问题呢？你在论文笔记里也提到了这是对空间信息处理的改进。这个我不明白。
> > 谢谢分享。
> 
> 对于这个问题我也没有合适的思路。
> 想请教下这个问题：https://github.com/Jiankai-Sun/charades-baseline-pytorch/blob/d34178a216c5333fb193dc731c77ceaad54bb346/utils/map.py#L26
> m_ap = np.mean(m_aps)
> m_ap = np.nanmean(m_aps)
> 这两种情况对结果会有影响吗，有什么不同吗，为啥我找到了在这个Charades数据集上面两种不一样的评价指标。使用m_ap = np.mean(m_aps)开始时一直都是nan，不知道后面会不会时正常的数字

**Comment by Yingying6** [comment]
nan那个问题我在跑timeception时也有，而且跑了很久也并没有正常。
说真的，大家都在用的这个map的写法，我觉得有点问题，但同样的map指标，如果用双流法的baseline算法跑，就不会有nan，而timeception的响应值就是很低
我没有QQ，我想把问题整理一下，在国庆节前咱们打个电话交流一下， 如果你觉得方便的话？把你电话发到我邮箱？yingyingzhong0621@gmail.com

**Comment by bensange123** [comment]
17602949285


 
---原始邮件---
发件人: "Yingying6"<notifications@github.com&gt;
发送时间: 2019年9月25日 11:55:18
收件人: "bensange123/Papers"<Papers@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"RenPengzhen"<1006963297@qq.com&gt;;
主题: Re: [bensange123/Papers] 纯时间卷积前的通道分组操作 (#2)



nan那个问题我在跑timeception时也有，而且跑了很久也并没有正常。
 说真的，大家都在用的这个map的写法，我觉得有点问题，但同样的map指标，如果用双流法的baseline算法跑，就不会有nan，而timeception的响应值就是很低
 我没有QQ，我想把问题整理一下，在国庆节前咱们打个电话交流一下， 如果你觉得方便的话？把你电话发到我邮箱？yingyingzhong0621@gmail.com

**Comment by pzhren** [comment]
nan的问题你解决了吗


 
---原始邮件---
发件人: "Yingying6"<notifications@github.com&gt;
发送时间: 2019年9月25日 11:55:18
收件人: "bensange123/Papers"<Papers@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"RenPengzhen"<1006963297@qq.com&gt;;
主题: Re: [bensange123/Papers] 纯时间卷积前的通道分组操作 (#2)



nan那个问题我在跑timeception时也有，而且跑了很久也并没有正常。
 说真的，大家都在用的这个map的写法，我觉得有点问题，但同样的map指标，如果用双流法的baseline算法跑，就不会有nan，而timeception的响应值就是很低
 我没有QQ，我想把问题整理一下，在国庆节前咱们打个电话交流一下， 如果你觉得方便的话？把你电话发到我邮箱？yingyingzhong0621@gmail.com
